modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="byg"
version="1.8"
displayName="BYG Test"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://biomesyougo.weebly.com/"
logoFile="logo.png"
authors="AOCAWOL, SodiumZH, MCreator"
description='''
An Adventure and Exploration mod with over 70 new biomes!
'''

[[dependencies.byg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



