 package net.potionstudios.byg;
 
 import net.minecraft.block.state.IBlockState;
 import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
 import net.minecraft.item.ItemStack;
 import net.minecraftforge.client.event.ModelRegistryEvent;
 import net.minecraftforge.client.model.ModelLoader;
 import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
 import net.minecraftforge.fml.relauncher.Side;
 import net.minecraftforge.fml.relauncher.SideOnly;
 import net.minecraftforge.oredict.OreDictionary;
 
 @Elementsbyg.ModElement.Tag
public class RegistryFire
extends Elementsbyg.ModElement {
	 public RegistryFire(Elementsbyg instance) {
		  super(instance, 2420);
		}
	 
	   public void init(FMLInitializationEvent event) {
		   // Leaves
		   Blocks.FIRE.setFireInfo(Aspen_leaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Baobableaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Birchleavesyellow.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Brownbirchleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Cherryleavespink.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Cherryleaveswhite.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Cikaleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Cypressleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Ebonyleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Enchantedleavesblue.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Enchantedleavespink.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Enchantedleavespurple.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Firleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Frozenoakleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Greatoakleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Hawthorn_leaves_flowering.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Hawthornberryleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Hawthornleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Hollyberryleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Hollyleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Ironwoodleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Jacarandaleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Mahogany_leaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Mangroveleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Mapleleavesred.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Mapleleavessilver.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Oakleavesdrybrown.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Oakleavesdrygreen.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Oakleavesorange.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Oakleavesred.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Orangebirchleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Orchardleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Orchardleavesapple.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Orchardleavesflowering.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Palm_leaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Paloverdeleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Paloverdeleavesflowering.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Pineleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Rainboweucalyptusleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Redbirchleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Redwoodleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Rowanberryleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Rowanleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Silver_apple_white_skyris_leaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Skyrisleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Skyrisleavesgreenapple.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Spruceleavesblue.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Spruceleavesorange.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Spruceleavesred.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Spruceleavesyellow.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Stellataleavespink.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Stellataleaveswhite.block, 30, 60);
		   Blocks.FIRE.setFireInfo(White_skyris_leaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Willowleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Witchhazelleaves.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Witchhazelleavesblooming.block, 30, 60);
		   Blocks.FIRE.setFireInfo(Zelkovaleaves.block, 30, 60);
		   
		   // Logs
		   Blocks.FIRE.setFireInfo(Aspen_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Aspen_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Baobab_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Baobablog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Blue_enchanted_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Cherry_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Cherrylog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Cika_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Cikalog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Cypress_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Cypresslog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Ebony_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Ebonylog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Enchantedlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Firlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Firwood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Frozen_oak_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Frozenoaklog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Great_oak_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Greatoaklog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Green_enchanted_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Greenenchantedlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Hawthorn_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Hawthornlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Holly_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Hollylog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Ironwood_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Ironwoodlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Jacaranda_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Jacarandalog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Mahogany_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Mahogany_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Mangrove_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Mangrovelog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Maple_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Maplelog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Palm_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Palm_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Palo_verde_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Paloverdelog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Pine_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Pinelog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Plant_stem.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Rainbow_eucalyptus_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Rainboweucalyptuslog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Redwood_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Redwoodlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Rowan_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Rowanlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Skyris_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Skyrislog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_aspen_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_aspen_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_baobab_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_baobab_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_blue_enchanted_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_blue_enchanted_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_cherry_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_cherry_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_cika_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_cika_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_cypress_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_cypress_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_ebony_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_ebony_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_great_oak_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_great_oak_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_green_enchanted_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_green_enchanted_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_hawthorn_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_hawthorn_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_holly_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_holly_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_ironwood_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_ironwood_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_jacaranda_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_jacaranda_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_mangrove_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_mangrove_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_maple_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_maple_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_palo_verde_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_palo_verde_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_pine_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_pine_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_rainbow_eucalyptus_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_rainbow_eucalyptus_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_redwood_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_redwood_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_rowan_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_rowan_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_skyris_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_skyris_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_willow_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_willow_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_witch_hazel_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_witch_hazel_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_zelkova_log.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Stripped_zelkova_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Strippedfirlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Strippedfirwood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Thorn_branches.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Thornblock.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Willow_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Willowlog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Witch_hazel_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Witchhazellog.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Zelkova_wood.block, 5, 5);
		   Blocks.FIRE.setFireInfo(Zelkovalog.block, 5, 5);
	   }
		   
		   
}
